name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read metrics
        id: metrics
        run: |
          if [ -f metrics.json ]; then
            TRAIN_ACC=$(jq -r '.train_accuracy' metrics.json)
            VAL_ACC=$(jq -r '.val_accuracy' metrics.json)
            TRAIN_LOSS=$(jq -r '.train_loss' metrics.json)
            VAL_LOSS=$(jq -r '.val_loss' metrics.json)
            echo "release_body=ðŸ§  Model Performance%0Aâœ… Train Accuracy: ${TRAIN_ACC}%0Aâœ… Val Accuracy: ${VAL_ACC}%0AðŸ“‰ Train Loss: ${TRAIN_LOSS}%0AðŸ“‰ Val Loss: ${VAL_LOSS}" >> $GITHUB_OUTPUT
          else
            echo "release_body=âš ï¸ No metrics.json found." >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.metrics.outputs.release_body }}
          files: |
            saved_models/pet_classifier.keras
            best_model.h5
            metrics.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
